language: php
php:
  - 5.3
  - 5.4
before_script:
  - git submodule update --init
  - cp phpunit.xml.dist phpunit.xml
  - ~/.nvm/nvm.sh run default tests/Guzzle/Tests/Http/server.js &
script: sudo phpunit
